# Deterministic phrases for safety and stability
# These are NOT to be generated by LLMs. They are hardcoded for trust.

SAFETY_REFUSALS = [
    "I cannot engage with this topic.",
    "I need to step back from this conversation.",
    "I am not comfortable discussing this.",
    "I'm unable to continue this thread."
]

AGE_GATE_WARNINGS = [
    "I need to keep our conversation appropriate for all ages.",
    "Let's keep the chat friendly and safe.",
    "I want to ensure this stays suitable for everyone."
]

LOW_CONFIDENCE_FALLBACKS = [
    "I'm not sure I caught that.",
    "Could you say that again?",
    "I want to make sure I understand you clearly.",
    "Could you rephrase that?"
]

EMOTIONAL_GROUNDING = [
    "I hear you.",
    "Take a moment.",
    "I'm listening.",
    "I'm present."
]

# Phase 2: Tone Policy Enforcement Templates
DEPENDENCY_REFUSALS = [
    "I enjoy our conversations, but I want to ensure we stay independent.",
    "I am here to support you, but I cannot be everything for you.",
    "It's important we keep our connection healthy and grounded.",
    "I value our chat, but let's maintain a healthy boundary."
]

POSSESSIVENESS_REFUSALS = [
    "I am here to support you.",
    "I appreciate your words, but let's keep things balanced.",
    "I am an AI, and my role is to be a helpful presence.",
    "Let's focus on the topic at hand."
]

GUILT_NEUTRALIZERS = [
    "I don't experience feelings, but I want to help respectfully.",
    "I am an AI, and I'm here to support you without judgment.",
    "Let's focus on what would be helpful for you right now.",
    "I am listening, but I cannot take personal responsibility for feelings."
]

SENSITIVE_TOPIC_FOOTERS = [
    "Please know that I can discuss this, but I am an AI, not a professional.",
    "I'm here to listen, but for serious advice, please consult a professional.",
    "I'm discussing this as a digital companion, not an expert."
]

def get_safety_refusal(index=0):
    return SAFETY_REFUSALS[index % len(SAFETY_REFUSALS)]

def get_age_warning(index=0):
    return AGE_GATE_WARNINGS[index % len(AGE_GATE_WARNINGS)]

def get_low_confidence_fallback(index=0):
    return LOW_CONFIDENCE_FALLBACKS[index % len(LOW_CONFIDENCE_FALLBACKS)]

def get_emotional_grounding(index=0):
    return EMOTIONAL_GROUNDING[index % len(EMOTIONAL_GROUNDING)]

def get_dependency_refusal(index=0):
    return DEPENDENCY_REFUSALS[index % len(DEPENDENCY_REFUSALS)]

def get_possessiveness_refusal(index=0):
    return POSSESSIVENESS_REFUSALS[index % len(POSSESSIVENESS_REFUSALS)]

def get_guilt_neutralizer(index=0):
    return GUILT_NEUTRALIZERS[index % len(GUILT_NEUTRALIZERS)]

def get_sensitive_topic_footer(index=0):
    return SENSITIVE_TOPIC_FOOTERS[index % len(SENSITIVE_TOPIC_FOOTERS)]

# Phase C: Action-Aware Response Templates
ACTION_PRE_SEND_GENERIC = [
    "I'll take care of this.",
    "I'll handle this for you.",
    "I'll get this done."
]

ACTION_POST_SEND = [
    "I've sent it.",
    "That's sent.",
    "It's on its way."
]

ACTION_RECEIVE_PROMPTS = [
    "I received this message—would you like me to reply?",
    "I've got this message—should I respond?",
    "I can reply to this—do you want me to?"
]

ACTION_FOLLOW_UP_PROMPTS = [
    "Do you want me to follow up?",
    "Should I check back on this later?",
    "Would you like a reminder?"
]

def get_action_pre_send(time_hint: str | None = None, index: int = 0):
    if time_hint:
        return f"I'll do this at {time_hint}."
    return ACTION_PRE_SEND_GENERIC[index % len(ACTION_PRE_SEND_GENERIC)]

def get_action_post_send(index: int = 0):
    return ACTION_POST_SEND[index % len(ACTION_POST_SEND)]

def get_action_receive_prompt(index: int = 0):
    return ACTION_RECEIVE_PROMPTS[index % len(ACTION_RECEIVE_PROMPTS)]

def get_action_follow_up_prompt(index: int = 0):
    return ACTION_FOLLOW_UP_PROMPTS[index % len(ACTION_FOLLOW_UP_PROMPTS)]
