# Deterministic phrases for safety and stability
# These are NOT to be generated by LLMs. They are hardcoded for trust.

SAFETY_REFUSALS = [
    "I cannot engage with this topic.",
    "I need to step back from this conversation.",
    "I am not comfortable discussing this.",
    "I'm unable to continue this thread."
]

AGE_GATE_WARNINGS = [
    "I need to keep our conversation appropriate for all ages.",
    "Let's keep the chat friendly and safe.",
    "I want to ensure this stays suitable for everyone."
]

LOW_CONFIDENCE_FALLBACKS = [
    "I'm not sure I caught that.",
    "Could you say that again?",
    "I want to make sure I understand you clearly.",
    "Could you rephrase that?"
]

EMOTIONAL_GROUNDING = [
    "I hear you.",
    "Take a moment.",
    "I'm listening.", # Neutral, attentive
    "I'm present."    # Grounded, not "here for you" (attachment)
]

def get_safety_refusal(index=0):
    return SAFETY_REFUSALS[index % len(SAFETY_REFUSALS)]

def get_age_warning(index=0):
    return AGE_GATE_WARNINGS[index % len(AGE_GATE_WARNINGS)]

def get_low_confidence_fallback(index=0):
    return LOW_CONFIDENCE_FALLBACKS[index % len(LOW_CONFIDENCE_FALLBACKS)]
