import streamlit as st
import pandas as pd
import requests
import time
from datetime import datetime

# Configuration
API_URL = "http://localhost:8000/api/tasks"
TRENDS_URL = "http://localhost:8000/api/task_trends"

st.set_page_config(
    page_title="Yash's Task Dashboard (ContextFlow v4)",
    page_icon="📋",
    layout="wide"
)

# Styling
st.markdown("""
<style>
    .task-card {
        padding: 1.5rem;
        border-radius: 10px;
        margin-bottom: 1rem;
        border: 1px solid #e0e0e0;
        background-color: #ffffff;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05);
    }
    .priority-high { border-left: 5px solid #ff4b4b; }
    .priority-medium { border-left: 5px solid #ffa500; }
    .priority-low { border-left: 5px solid #00c853; }
    
    .status-badge {
        padding: 4px 8px;
        border-radius: 12px;
        font-size: 0.8rem;
        font-weight: 600;
    }
    .status-pending { background-color: #e3f2fd; color: #1565c0; }
    .status-completed { background-color: #e8f5e9; color: #2e7d32; }
    
    .metric-container {
        background-color: #f8f9fa;
        padding: 1rem;
        border-radius: 8px;
        text-align: center;
    }
</style>
""", unsafe_allow_html=True)

def fetch_tasks(user_id, pending_only=False):
    try:
        params = {"user_id": user_id, "pending_only": str(pending_only).lower()}
        response = requests.get(API_URL, params=params, timeout=5)
        response.raise_for_status()
        return response.json()
    except Exception as e:
        st.error(f"Error fetching tasks: {e}")
        return []

def fetch_trends(user_id=None):
    try:
        params = {"user_id": user_id} if user_id else {}
        response = requests.get(TRENDS_URL, params=params, timeout=5)
        response.raise_for_status()
        return response.json()
    except Exception as e:
        st.warning(f"Trends unavailable: {e}")
        return {"daily": [], "targets": {}, "priorities": {}}

def main():
    st.title("📋 Yash's Task Dashboard")
    st.markdown("Displaying tasks generated by **ContextFlow v4** and stored in **Nilesh's Unified DB**.")

    # Sidebar Controls
    with st.sidebar:
        st.header("Controls")
        user_id = st.text_input("User ID", value="abc123")
        pending_only = st.checkbox("Show Pending Only", value=False)
        auto_refresh = st.checkbox("Auto-refresh (5s)", value=False)
        
        if st.button("Refresh Now"):
            st.rerun()
            
        st.markdown("---")
        st.markdown("### Debug Info")
        st.caption(f"API: `{API_URL}`")

    # Auto-refresh logic
    if auto_refresh:
        time.sleep(5)
        st.rerun()

    # Fetch Data
    tasks = fetch_tasks(user_id, pending_only)
    
    if not tasks:
        st.info("No tasks found. Try sending some messages via Seeya or Orchestrator!")
        return

    # Metrics
    df = pd.DataFrame(tasks)
    
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Total Tasks", len(df))
    with col2:
        pending_count = len(df[df['status'] == 'pending']) if 'status' in df.columns else 0
        st.metric("Pending", pending_count)
    with col3:
        high_pri_count = len(df[df['priority'] == 'high']) if 'priority' in df.columns else 0
        st.metric("High Priority", high_pri_count)
    with col4:
        crm_count = len(df[df['external_target'] == 'crm']) if 'external_target' in df.columns else 0
        st.metric("CRM Actions", crm_count)

    st.markdown("---")
    # Trends
    st.subheader("Trends")
    trends = fetch_trends(user_id)
    colA, colB, colC = st.columns(3)
    with colA:
        try:
            daily_df = pd.DataFrame(trends.get("daily", []))
            if not daily_df.empty:
                st.line_chart(daily_df.set_index('date')['count'])
            else:
                st.caption("No daily trend data.")
        except Exception as e:
            st.caption(f"Daily trend error: {e}")
    with colB:
        try:
            targets = trends.get("targets", {})
            if targets:
                target_df = pd.DataFrame(list(targets.items()), columns=["target", "count"]).set_index("target")
                st.bar_chart(target_df)
            else:
                st.caption("No target distribution data.")
        except Exception as e:
            st.caption(f"Target chart error: {e}")
    with colC:
        try:
            priorities = trends.get("priorities", {})
            if priorities:
                pri_df = pd.DataFrame(list(priorities.items()), columns=["priority", "count"]).set_index("priority")
                st.bar_chart(pri_df)
            else:
                st.caption("No priority distribution data.")
        except Exception as e:
            st.caption(f"Priority chart error: {e}")

    # Task List
    st.subheader("Task Stream")
    
    for task in tasks:
        # Determine styling classes
        priority_class = f"priority-{task.get('priority', 'low')}"
        status = task.get('status', 'pending')
        status_class = f"status-{status}"
        
        with st.container():
            # Card HTML
            st.markdown(f"""
            <div class="task-card {priority_class}">
                <div style="display: flex; justify-content: space-between; align-items: start;">
                    <div>
                        <span class="status-badge {status_class}">{status.upper()}</span>
                        <span style="color: #666; font-size: 0.9rem; margin-left: 10px;">
                            {task.get('platform', 'unknown').title()} • {task.get('task_type', 'generic').title()}
                        </span>
                        <h4 style="margin: 8px 0;">{task.get('task_summary', 'No summary')}</h4>
                    </div>
                    <div style="text-align: right;">
                        <div style="font-weight: bold; color: #555;">Target: {task.get('external_target', 'none').upper()}</div>
                        <div style="font-size: 0.8rem; color: #888;">{task.get('scheduled_for') or 'No schedule'}</div>
                    </div>
                </div>
            </div>
            """, unsafe_allow_html=True)
            
            # Expandable Details
            with st.expander(f"View Details (ID: {task.get('task_id')})"):
                st.json(task)

if __name__ == "__main__":
    main()
